server:
  port: 17080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: chaskawear-catalogo-categorias
              uri: lb://chaskawear-catalogo-ms
              predicates:
                - Path=/api/v1/categorias/**
            - id: chaskawear-catalogo-productos
              uri: lb://chaskawear-catalogo-ms
              predicates:
                - Path=/api/v1/productos/**
            - id: chaskawear-orden-ordenes
              uri: lb://chaskawear-orden-ms
              predicates:
                - Path=/api/v1/ordenes/**
            - id: chaskawear-orden-detalles
              uri: lb://chaskawear-orden-ms
              predicates:
                - Path=/api/v1/orden-detalles/**
            - id: chaskawear-inventario-stocks
              uri: lb://chaskawear-inventario-ms
              predicates:
                - Path=/api/v1/stocks/**
            - id: chaskawear-inventario-movimientos
              uri: lb://chaskawear-inventario-ms
              predicates:
                - Path=/api/v1/movimientos/**
            - id: chaskawear-pago-pagos
              uri: lb://chaskawear-pago-ms
              predicates:
                - Path=/api/v1/pagos/**
            - id: chaskawear-pago-transacciones
              uri: lb://chaskawear-pago-ms
              predicates:
                - Path=/api/v1/transacciones/**
            - id: chaskawear-auth-usuarios
              uri: lb://chaskawear-auth-ms
              predicates:
                - Path=/api/v1/usuarios/**
            - id: chaskawear-auth-roles
              uri: lb://chaskawear-auth-ms
              predicates:
                - Path=/api/v1/roles/**
            - id: chaskawear-notificacion-avisos
              uri: lb://chaskawear-notificacion-ms
              predicates:
                - Path=/api/v1/avisos/**
            - id: chaskawear-notificacion-canales
              uri: lb://chaskawear-notificacion-ms
              predicates:
                - Path=/api/v1/canales/**

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:17761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
