name: chaskawear-infra-prod

services:
  chaskawear-config:
    build:
      context: ./pagatu-config
      dockerfile: Dockerfile
    container_name: chaskawear-config
    restart: unless-stopped
    ports:
      - "27888:8888"
    volumes:
      - ./pagatu-config/config-repo:/config-repo
    environment:
      SERVER_PORT: 8888
      SPRING_PROFILES_ACTIVE: native
      CONFIG_REPO_LOCATION: file:/config-repo
    networks:
      - chaskawear-prod-net

networks:
  chaskawear-prod-net:
    name: chaskawear-prod-net
