name: chaskawear-catalogo-dev

services:
  postgres-catalogo-dev:
    image: postgres:16-alpine
    container_name: chaskawear-postgres-catalogo-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: chaskawear_catalogo_db
      POSTGRES_USER: chaska
      POSTGRES_PASSWORD: chaska
    ports:
      - "16432:5432"
    volumes:
      - chaskawear_catalogo_dev_data:/var/lib/postgresql/data

volumes:
  chaskawear_catalogo_dev_data:
