name: chaskawear-orden-prod

services:
  postgres-orden:
    image: postgres:16-alpine
    container_name: chaskawear-postgres-orden
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - chaskawear_orden_data:/var/lib/postgresql/data
    ports:
      - "26434:5432"
    networks:
      - chaskawear-orden-int

  chaskawear-orden-ms:
    build: .
    restart: unless-stopped
    depends_on:
      postgres-orden:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
      DB_HOST: chaskawear-postgres-orden
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    volumes:
      - ./logs:/app/logs
    networks:
      - chaskawear-orden-int
      - chaskawear-prod-net

volumes:
  chaskawear_orden_data:

networks:
  chaskawear-orden-int:
    name: chaskawear-orden-int
  chaskawear-prod-net:
    external: true
