name: chaskawear-orden-dev

services:
  postgres-orden-dev:
    image: postgres:16-alpine
    container_name: chaskawear-postgres-orden-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: chaskawear_orden_db
      POSTGRES_USER: chaska
      POSTGRES_PASSWORD: chaska
    ports:
      - "16434:5432"
    volumes:
      - chaskawear_orden_dev_data:/var/lib/postgresql/data

volumes:
  chaskawear_orden_dev_data:
