name: chaskawear-auth-dev

services:
  postgres-auth-dev:
    image: postgres:16-alpine
    container_name: chaskawear-postgres-auth-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: chaskawear_auth_db
      POSTGRES_USER: chaska
      POSTGRES_PASSWORD: chaska
    ports:
      - "16440:5432"
    volumes:
      - chaskawear_auth_dev_data:/var/lib/postgresql/data

volumes:
  chaskawear_auth_dev_data:
